# M.Amintoosi

Tensorflow

In [1]:
import tensorflow as tf

a = tf.constant([[1, 2], [3, 4]])                 
b = tf.add(a, 1)

a.numpy()
# array([[1, 2],
#        [3, 4]], dtype=int32)

b.numpy()
# array([[2, 3],
#        [4, 5]], dtype=int32)

tf.multiply(a, b).numpy()
# array([[ 2,  6],
#        [12, 20]], dtype=int32)

array([[ 2,  6],
       [12, 20]])

In [7]:
x = a.numpy()
x[0,0] = 8
# a[0,1].assign(9)
print(x, a)

[[8 2]
 [3 4]] tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
