# M.Amintoosi

Gradient in PyTorch

https://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html

In [1]:
import torch

a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)
print(a)
print(b)

tensor([2., 3.], requires_grad=True)
tensor([6., 4.], requires_grad=True)


In [2]:
Q = 3*a**3 - b**2
print(Q)

tensor([-12.,  65.], grad_fn=<SubBackward0>)


In [3]:
external_grad = torch.tensor([1., 1.])
Q.backward(gradient=external_grad)

In [9]:
print(a.grad)
print(b.grad)

tensor([ 72., 162.])
tensor([-24., -16.])


In [5]:
print(9*a**2 == a.grad)
print(-2*b == b.grad)

tensor([True, True])
tensor([True, True])


In [10]:
a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)
Q = 3*a**3 - b**2
print(Q)
Q.sum().backward()
# print(Q)

tensor([-12.,  65.], grad_fn=<SubBackward0>)


In [11]:
print(9*a**2 == a.grad)
print(-2*b == b.grad)

tensor([True, True])
tensor([True, True])
